[default.oauth.google]
provider = "Google"
client_id = ""
client_secret = ""
redirect_uri = ""

[default.oauth.github]
provider = "GitHub"
client_id = "..."
client_secret = "..."
redirect_uri = "http://localhost:9797/auth/google"
